kind: pipeline
name: default

trigger:
  branch:
    - master

steps:
  - name: build-and-test
    image: golang
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - go build
      - go test
      - go test -race -coverprofile=coverage.txt -covermode=atomic
      # the documented "bash <(curl -s https://codecov.io/bash)" doesn't work
      - curl -s --output codecov.sh https://codecov.io/bash
      - bash codecov.sh

  - name: publish
    when:
      branch:
        - master
      event:
        - push
    image: node
    environment:
      GH_TOKEN:
        from_secret: gh_token
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - npm install -g semantic-release '@semantic-release/changelog' '@semantic-release/git'
      - semantic-release
