kind: pipeline
name: default

trigger:
  branch:
    - master

# we want tags (for go generate), so we need to make cloning an explicit step
# so we can actually request the tags
clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      tags: true

  - name: build-and-test
    image: golang:1.14.1
    commands:
      - go generate -v
      - go build -v
      - go test -v
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic

  - name: codecov
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token

  - name: release
    when:
      branch:
        - master
      event:
        - push
    image: jaredreisinger/semantic-release:latest
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
