// +build ignore

package main

import (
	"fmt"
	"html/template"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

var buildTemplate = template.Must(template.New("build_info").Parse(
	`// Code generated by 'go generate' -- DO NOT EDIT.

package main

const (
	gitVersion = "{{ .GitVersion }}"
	buildDate  = "{{ .BuildDate }}"
)
`))

func main() {
	info := &struct {
		GitVersion string
		BuildDate  string
	}{}

	cmd := exec.Command("git", "describe", "--tags", "--dirty")
	b, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}

	info.GitVersion = strings.TrimSpace(fmt.Sprintf("%s", b))
	info.BuildDate = time.Now().Format(time.RFC3339)

	file, err := os.Create("build_info.go")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	// buf := &bytes.Buffer{}
	err = buildTemplate.Execute(file, info)
	if err != nil {
		log.Fatal(err)
	}
}
