#!/bin/bash
docker build \
  --build-arg SOURCE_COMMIT="${SOURCE_COMMIT}" \
  --build-arg DOCKER_TAG="${DOCKER_TAG}" \
  --build-arg BUILD_DATE="$(date --utc --rfc-3339=seconds)" \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME \
  .
